### ISSUE TITLE
Problem with restarts

### ISSUE THREAD

**Issue by vadim0x60** [vadim0x60/cibi#37]
Officially we support restarts, but when you actually restart an experiment sometimes this happens:

```

Traceback (most recent call last):
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'then' and 'else' must have the same size.  but received: [4,23] vs. [4,13]
	 [[{{node local/policy/rnn/while/Select_2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcs001/20194474/cibi/cibi/train.py", line 132, in run_experiments
    rollout = agent.attend_gym(env, max_reps=max_episode_length, render=render)
  File "/home/mcs001/20194474/cibi/cibi/agent.py", line 31, in attend_gym
    self.init()
  File "/home/mcs001/20194474/cibi/cibi/scrum_master.py", line 82, in init
    self.reprogram()
  File "/home/mcs001/20194474/cibi/cibi/scrum_master.py", line 145, in reprogram
    self.write_programs()
  File "/home/mcs001/20194474/cibi/cibi/scrum_master.py", line 136, in write_programs
    programs = self.lead_developer.write_programs(self.archive_branch)
  File "/home/mcs001/20194474/cibi/cibi/senior_developer.py", line 286, in write_programs
    return self.developer.write_programs(self.session, inspiration_branch)
  File "/home/mcs001/20194474/cibi/cibi/senior_developer.py", line 182, in write_programs
    return self.model.write_programs(session, inspiration_branch)
  File "/home/mcs001/20194474/cibi/cibi/lm.py", line 653, in write_programs
    self.sampled_batch.log_probs])
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/mcs001/20194474/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'then' and 'else' must have the same size.  but received: [4,23] vs. [4,13]
	 [[node local/policy/rnn/while/Select_2 (defined at /.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'local/policy/rnn/while/Select_2':
  File "/cibi/cibi/train.py", line 161, in <module>
    run_experiments()
  File "/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/cibi/cibi/train.py", line 126, in run_experiments
    train_dir, events_dir, scrum_config, seed_codebase) as agent:
  File "/cibi/cibi/scrum_master.py", line 163, in hire_team
    for dev in developers]
  File "/cibi/cibi/scrum_master.py", line 163, in <listcomp>
    for dev in developers]
  File "/cibi/cibi/senior_developer.py", line 250, in hire
    self.set_language(language)
  File "/cibi/cibi/senior_developer.py", line 127, in set_language
    verbose_level=model_v)
  File "/cibi/cibi/lm.py", line 318, in __init__
    loop_fn=loop_fn)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn.py", line 1252, in raw_rnn
    swap_memory=swap_memory)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2170, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn.py", line 1234, in body
    emit_output = _copy_some_through(zero_emit, emit_output)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn.py", line 1232, in _copy_some_through
    return nest.map_structure(copy_fn, current, candidate)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 536, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 536, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn.py", line 1230, in copy_fn
    return array_ops.where(elements_finished, cur_i, cand_i)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3759, in where
    return gen_math_ops.select(condition=condition, x=x, y=y, name=name)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 9439, in select
    "Select", condition=condition, t=x, e=y, name=name)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by vadim0x60** [comment]
Probably fixed in d3d835ca2a406af769df5a445a2a612cfc5fdde9
Re-open if necessary
